[project]
name = "help"
version = "0.1.0"
description = "The https://t-strings.help/ website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    #    "sphinx>=8.2.3",
    "jupyterlite-core[all]>=0.6.0b0",
    "jupyterlite-pyodide-kernel>=0.6.0b1",
    "jupytext>=1.17.1",
]
